### ISSUE TITLE
OSMemCreateAssumes 32bit pointers

### ISSUE THREAD

**Issue by heyneman** [weston-embedded/uC-OS2#7]
In the call to `OSMemCreate()`, if arg checking is enabled, the pointer to the start of the partition is cast to an integer in order to verify its aligned to store pointers.

When I compile this on a 64bit system I get compiler warnings about the cast to a smaller type. uC-CPU defines an `OS_ADDR` type, which would be ideal to use here, but uC-OS2 isn't required to use it. My workaround so far has been to add a similar typedef in os_cpu.h (along with the others like INT32U currently used in the cast).

To reproduce; compile os_mem.c on Ubuntu 18.04 (64bit) using gcc 7.5.0.

https://github.com/weston-embedded/uC-OS2/blob/28c58eb58eacf7bfcefca6a5ef866ea04e6a7e29/Source/os_mem.c#L106

**Comment by forg0ne** [comment]
Thank you for reporting this.
Unfortunately, there is no easy way for us to resolve it.
We are reluctant to include a dependency on uC-CPU for legacy support reasons.
Neither can we use INT64U because it is only defined for a couple of ports.

Because this is an edge-case, the best approach in our opinion is to document it as an errata with a workaround for those who encounter it.

**Comment by forg0ne** [comment]
Errata for uCOS-III can be found [here](https://micrium.atlassian.net/wiki/spaces/osiidoc/pages/683016197/ERRATA).

**Comment by heyneman** [comment]
@forg0ne Just for my understanding, why would adding a `typedef <...> OS_ADDR` line in os_cpu.h (per port) not be an easy way to resolve it?

Then `OSMemCreate()` can use that type internally rather than assuming 32b.
